package constant

var (
	SERVER_PORT    = 5002
	ADMIN_PASSWORD = "" //省的GitHub跟我说我随便填的密码是涉嫌泄露

	SUCCESS_STATUS    = "SUCCESS"
	FAILURE_STATUS    = "FAILURE"
	INVALID_CODE      = "CODE不正确"
	INVALID_AUTH_KEY  = "INVALID_AUTH_KEY"
	INVALID_TIMESTAMP = "INVALID_TIMESTAMP"

	PARAMS_ERR = "PARAMS_ERR"
	SERVER_ERR = "SERVER_ERR"
)
